from __future__ import annotations

from pathlib import Path
from typing import Optional

import jinja2
import yaml

_TEMPLATES_DIR = Path(__file__).parent / "templates"
_DEFAULTS_DIR = Path(__file__).parent / "defaults"


def find_cargo_toml(project_path: Path) -> Path:
    """Find and validate Cargo.toml in the project directory."""
    cargo_toml = project_path / "Cargo.toml"
    if not cargo_toml.exists():
        raise FileNotFoundError(
            f"No Cargo.toml found in {project_path}. "
            "Run this command from a Rust project directory, or use --path."
        )
    content = cargo_toml.read_text()
    if "[workspace]" in content:
        raise ValueError(
            f"Found a workspace Cargo.toml at {cargo_toml}. "
            "CodeEvolution v1 supports single crates only. "
            "Point --path at a specific member crate instead."
        )
    return cargo_toml


def scan_rs_files(project_path: Path) -> list[Path]:
    """Find all .rs files under src/."""
    src_dir = project_path / "src"
    if not src_dir.exists():
        return []
    return sorted(src_dir.rglob("*.rs"))


def insert_evolve_markers(rs_file: Path) -> None:
    """Wrap file content in EVOLVE-BLOCK markers if not already present."""
    content = rs_file.read_text()
    if "EVOLVE-BLOCK-START" in content:
        return
    wrapped = f"// EVOLVE-BLOCK-START\n{content}// EVOLVE-BLOCK-END\n"
    rs_file.write_text(wrapped)


def generate_codeevolve_dir(
    project_path: Path,
    rs_files: list[Path],
    custom_benchmark: Optional[str] = None,
    custom_benchmark_regex: Optional[str] = None,
) -> Path:
    """Generate the .codeevolve/ directory with config, evaluator, and README."""
    codeevolve_dir = project_path / ".codeevolve"
    codeevolve_dir.mkdir(exist_ok=True)

    # --- Generate evolution.yaml ---
    with open(_DEFAULTS_DIR / "evolution.yaml") as f:
        config_data = yaml.safe_load(f)

    if custom_benchmark:
        config_data["benchmarks"]["custom_command"] = custom_benchmark
    if custom_benchmark_regex:
        config_data["benchmarks"]["custom_command_score_regex"] = custom_benchmark_regex

    config_path = codeevolve_dir / "evolution.yaml"
    with open(config_path, "w") as f:
        yaml.dump(config_data, f, default_flow_style=False, sort_keys=False)

    # --- Generate evaluator.py ---
    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(str(_TEMPLATES_DIR)),
        keep_trailing_newline=True,
    )
    template = env.get_template("evaluator.py.j2")
    codeevolve_package_path = str(Path(__file__).parent.parent.resolve())

    evaluator_code = template.render(
        project_name=project_path.name,
        codeevolve_package_path=codeevolve_package_path.replace("\\", "/"),
        config_path=str(config_path.resolve()).replace("\\", "/"),
    )
    (codeevolve_dir / "evaluator.py").write_text(evaluator_code)

    # --- Generate README.md ---
    file_list = "\n".join(f"  - {f.relative_to(project_path)}" for f in rs_files)
    readme = f"""# CodeEvolution Setup

This directory was generated by `codeevolve init`. Here's what each file does:

## Files

- **evolution.yaml** — Configuration for the evolutionary optimizer. Controls which
  Ollama models to use, how many iterations to run, fitness weights, and more.
  Edit this to tune the evolution. All fields have sensible defaults.

- **evaluator.py** — The fitness function that scores each code candidate. This is
  called automatically by the optimizer. You generally don't need to edit this.

## Evolved Files

The following source files have been marked for evolution:
{file_list}

Each file has `// EVOLVE-BLOCK-START` and `// EVOLVE-BLOCK-END` markers around
the code that the optimizer is allowed to change. You can move these markers to
control which parts of your code get evolved.

## How to Run

1. Make sure Ollama is running: `ollama serve`
2. Pull the required models (first time only):
   - `ollama pull qwen2.5-coder:7b-instruct-q4_K_M`
   - `ollama pull qwen2.5-coder:1.5b-instruct-q4_K_M`
3. Start the evolution: `codeevolve run`

The optimizer will try hundreds of variations of your code, keeping only the ones
that compile, pass tests, and score well on code quality metrics.

Results are saved to `.codeevolve/output/`. The best version is in `output/best/`.

## How It Works

Each candidate goes through 4 checks:
1. **Build + Tests** — Must compile and pass all tests (hard requirement)
2. **Clippy Analysis** — Fewer warnings = better score
3. **Performance** — Faster compile time and smaller binary = better score
4. **AI Review** — An AI model rates code quality (only for top candidates)

Press Ctrl+C at any time to stop. Your best result so far is always saved.
"""
    (codeevolve_dir / "README.md").write_text(readme)

    return codeevolve_dir
